version: '3.8'
services:
  PF:
    # build: 
      # context: .
    image: test
    volumes:
      # - "%cd%/Code":"/Code"
      - .:/App
    ports:
      - "8050:8050"
# volumes:
#   # "%cd%/Code":
#   /Code:

# to run:
# 1. Install docker desktop and make sure the docker engine is running
# 2. Open cmd or terminal and navigate to this working directory
# 3. run the following command: docker-compose run --rm PF
# In the command above, "PF" refers to the service from the docker-compose file. 
# The name of the service may change in which case the command would need to be updated.