---
title: "R Notebook"
output: html_notebook
---

```{r}
# library(tidyverse)
library(tidytable)
library(rmgarch)
library(MTS)
library(forecast)
```

```{r}
print(getwd())
```


```{r}
training_data = read.csv(r"(Datasets/residuals.csv)", row.names = 1)
```

```{r}
colnames(training_data)
```


```{r}
head(training_data,5)
# training_data

# sapply(training_data, class)
```

```{r}
which(colnames(training_data)=="HourlyPrecipitation")
```


```{r}
dummified_data <- training_data %>% get_dummies(drop_first = TRUE)
dummified_data = subset(dummified_data, select = !(names(dummified_data) %in% c("HourlyPrecipitation")))
```

```{r}
colnames(dummified_data)
```


Separate Energy Demand and Temperature. PCA the rest.
```{r}
not_pca_vars = c("Energy.Demand..MWH.", "HourlyDryBulbTemperature")
```


```{r}
not_pca_data <- dummified_data[, c("Energy.Demand..MWH.", "HourlyDryBulbTemperature")]
pca_data <- subset(dummified_data, select = !(names(dummified_data) %in% not_pca_vars))
scaled_data <- scale(pca_data)
# scaled_data
```

```{r}
pca_result <- prcomp(scaled_data)
```


```{r}
# # Principal components
# pca_result$rotation
# 
# # Standard deviations of principal components
# pca_result$sdev

# Proportion of variance explained by each principal component
prop_var <- (pca_result$sdev^2) / sum(pca_result$sdev^2)
prop_var
```

```{r}
# Scree plot
pca_keep <- prop_var > 1e-3
# pca_keep
orthogonal_data <- scaled_data %*% pca_result$rotation[,pca_keep]
dim(pca_result$rotation[,pca_keep])
dim(scaled_data)
  # as.data.frame(pca_result$rotation[,pca_keep])
# HOW TO CONVERT THIS INTO A DATAFRAME WITH COLUMNS...
dim(orthogonal_data)
# orthogonal_data
```

```{r}
test <- cbind(not_pca_data, orthogonal_data)[,1:5]
test
```

```{r}
library(vars)
```

```{r}

# Create a data frame or matrix containing all variables
# Here, 'data' is your data frame or matrix containing all variables
# endogenous_vars and exogenous_vars contain the names of the respective variables
endog_data <- test[, "Energy.Demand..MWH."]
exog_data <- subset(test, select = !(names(test) %in% c("Energy.Demand..MWH.")))
# endog_data
# exog_data
library(vars)

var_model <- vars::VAR(test, p=10, type="const")

```

```{r}
summary(var_model)
```

```{r}
predictions <- predict(var_model, n.ahead=1000)
predictions <- predictions$fcst$Energy.Demand..MWH.
```

```{r}
plot(predictions[,"fcst"])
```

Now fit the GARCH model
```{r}

```


```{r}
predictions <- VARpred(var_model, h=10, output = FALSE)
```


```{r}
predictions
plot(predictions)
```






```{r}
times <- training_data %>% rownames()
print(times)
```



Fit multivariate GARCH model
```{r}
time_series_object <- ts(training_data, start = c(2022, 1), frequency = 24)  # Frequency for hourly data is 24
```









